// const africanSubjects = [
//   'subject:"Nigerian fiction"',
//   'subject:"African fiction"',
//   'subject:"African poetry"',
//   'subject:"African romance"',
//   'subject:"Afrofuturism"',
//   'subject:"Ghanaian literature"',
//   'subject:"Kenyan literature"',
//   'subject:"South African fiction"',
//   'subject:"Ethiopian literature"',
//   'subject:"Diaspora literature"',
//   'subject:"Postcolonial literature"',
//   'subject:"African fantasy"',
//   'subject:"African sci-fi"',
//   'subject:"African mythology"',
//   'subject:"African history"',
//   'subject:"Maghrebi literature"',
//   'subject:"East African literature"',
//   'subject:"West African fiction"',
//   'subject:"Southern African literature"',
//   'subject:"Sudanese literature"',
//   'subject:"Somali literature"',
//   'subject:"Senegalese literature"',
//   'subject:"Cameroonian literature"',
//   'subject:"Zimbabwean fiction"',
//   'subject:"Ugandan literature"',
//   'subject:"African feminism"',
//   'subject:"African political fiction"',
//   'subject:"African short stories"',
//   'subject:"African drama"',
//   'subject:"Afropunk fiction"',
//   'subject:"Contemporary African fiction"',
// ];

const globalSubjects = [
  // 'subject:"Literary fiction"',
  // 'subject:"Fantasy fiction"',
  // 'subject:"Science fiction"',
  // 'subject:"Historical fiction"',
  // 'subject:"Mystery fiction"',
  // 'subject:"Thriller fiction"',
  // 'subject:"Romance fiction"',
  // 'subject:"Young adult fiction"',
  // 'subject:"Biography"',
  // 'subject:"Memoir"',
  // 'subject:"Poetry"',
  // 'subject:"Drama"',
  // 'subject:"Philosophy"',
  // 'subject:"Psychology"',
  // 'subject:"Dystopian fiction"',
  // 'subject:"Magical realism"',
  // 'subject:"Crime fiction"',
  // 'subject:"Horror fiction"',
  // 'subject:"Cyberpunk"',
  // 'subject:"Steampunk"',
  // 'subject:"Epic fantasy"',
  // 'subject:"Space opera"',
  // 'subject:"Psychological thriller"',
  // 'subject:"Cozy mystery"',
  // 'subject:"Contemporary romance"',
  // 'subject:"New adult fiction"',
  // 'subject:"Graphic novels"',
  // 'subject:"Creative non-fiction"',
  // 'subject:"True crime"',
  // 'subject:"Self-help"',
  // 'subject:"Sociology"',
  // 'subject:"Anthologies"',
  // 'subject:"Short stories"',
  // 'subject:"Essays"',
  // 'subject:"Satire"',
  'subject:"Mythology"',
  'subject:"Cultural studies"',
  'subject:"Historical biography"',
];

// const globalAuthors = [
//   'inauthor:"William Shakespeare"',
//   'inauthor:"Jane Austen"',
//   'inauthor:"Charles Dickens"',
//   'inauthor:"Mark Twain"',
//   'inauthor:"Leo Tolstoy"',
//   'inauthor:"Fyodor Dostoevsky"',
//   'inauthor:"Ernest Hemingway"',
//   'inauthor:"F. Scott Fitzgerald"',
//   'inauthor:"Virginia Woolf"',
//   'inauthor:"George Orwell"',
//   'inauthor:"Edgar Allan Poe"',
//   'inauthor:"Mary Shelley"',
//   'inauthor:"Charlotte Brontë"',
//   'inauthor:"Emily Brontë"',
//   'inauthor:"Anne Brontë"',
//   'inauthor:"Homer"',
//   'inauthor:"Dante Alighieri"',
//   'inauthor:"Stephen King"',
//   'inauthor:"J.K. Rowling"',
//   'inauthor:"George R.R. Martin"',
//   'inauthor:"J.R.R. Tolkien"',
//   'inauthor:"C.S. Lewis"',
//   'inauthor:"Dan Brown"',
//   'inauthor:"John Grisham"',
//   'inauthor:"Nicholas Sparks"',
//   'inauthor:"Gillian Flynn"',
//   'inauthor:"Suzanne Collins"',
//   'inauthor:"Rick Riordan"',
//   'inauthor:"John Green"',
//   'inauthor:"Rainbow Rowell"',
//   'inauthor:"Toni Morrison"',
//   'inauthor:"Gabriel García Márquez"',
//   'inauthor:"Haruki Murakami"',
//   'inauthor:"Salman Rushdie"',
//   'inauthor:"Margaret Atwood"',
//   'inauthor:"Kazuo Ishiguro"',
//   'inauthor:"Zadie Smith"',
//   'inauthor:"Cormac McCarthy"',
//   'inauthor:"Maya Angelou"',
//   'inauthor:"James Baldwin"',
//   'inauthor:"Agatha Christie"',
//   'inauthor:"Arthur Conan Doyle"',
//   'inauthor:"Isaac Asimov"',
//   'inauthor:"Ray Bradbury"',
//   'inauthor:"Philip K. Dick"',
//   'inauthor:"Tom Clancy"',
// ];

// const africanAuthors = [
//   'inauthor:"Chinua Achebe"',
//   'inauthor:"Chimamanda Ngozi Adichie"',
//   'inauthor:"Wole Soyinka"',
//   'inauthor:"Ben Okri"',
//   'inauthor:"Teju Cole"',
//   'inauthor:"Ayobami Adebayo"',
//   'inauthor:"Ngũgĩ wa Thiong\'o"',
//   'inauthor:"Nadine Gordimer"',
//   'inauthor:"J.M. Coetzee"',
//   'inauthor:"NoViolet Bulawayo"',
//   'inauthor:"Nnedi Okorafor"',
//   'inauthor:"Ama Ata Aidoo"',
//   'inauthor:"Mariama Bâ"',
//   'inauthor:"Dinaw Mengestu"',
//   'inauthor:"Tomi Adeyemi"',
//   'inauthor:"Marlon James"',
//   'inauthor:"Buchi Emecheta"',
//   'inauthor:"Helon Habila"',
//   'inauthor:"Flora Nwapa"',
//   'inauthor:"Tsitsi Dangarembga"',
//   'inauthor:"Okey Ndibe"',
//   'inauthor:"Sefi Atta"',
//   'inauthor:"Chigozie Obioma"',
//   'inauthor:"Akwaeke Emezi"',
//   'inauthor:"Abubakar Adam Ibrahim"',
//   'inauthor:"Elechi Amadi"',
//   'inauthor:"Christopher Okigbo"',
//   'inauthor:"Léopold Sédar Senghor"',
//   'inauthor:"Tayeb Salih"',
//   'inauthor:"Naguib Mahfouz"',
//   'inauthor:"Abdulrazak Gurnah"',
//   'inauthor:"Petina Gappah"',
//   'inauthor:"Yaa Gyasi"',
//   'inauthor:"Binyavanga Wainaina"',
//   'inauthor:"Emezi Akwaeke"',
//   'inauthor:"Ken Saro-Wiwa"',
// ];

// const awardQueries = [
//   'subject:"Booker Prize"',
//   'subject:"Caine Prize"',
//   'subject:"Commonwealth Writers Prize"',
//   'subject:"Nobel Prize Literature"',
//   'subject:"Pulitzer Prize for Fiction"',
//   'subject:"National Book Award"',
//   'subject:"International Booker Prize"',
//   'subject:"Women\'s Prize for Fiction"',
//   'subject:"Hugo Award"',
//   'subject:"Nebula Award"',
//   'subject:"PEN/Faulkner Award"',
//   'subject:"Neustadt International Prize"',
//   'subject:"Miles Franklin Award"',
//   'subject:"Costa Book Award"',
//   'subject:"Dublin Literary Award"',
//   'subject:"Kirkus Prize"',
//   'subject:"Anisfield-Wolf Book Award"',
//   'subject:"Governor General\'s Literary Award"',
//   'subject:"Scotiabank Giller Prize"',
//   'subject:"Stella Prize"',
//   'subject:"Dylan Thomas Prize"',
//   'subject:"Rathbones Folio Prize"',
//   'subject:"Noma Award for Publishing in Africa"',
//   'subject:"9mobile Prize for Literature"',
// ];

// const publisherQueries = [
//   'inpublisher:"Cassava Republic"',
//   'inpublisher:"Farafina"',
//   'inpublisher:"Kwela"',
//   'inpublisher:"Masobe"',
//   'inpublisher:"Jacana"',
//   'inpublisher:"Ouida Books"',
//   'inpublisher:"Parrésia Publishers"',
//   'inpublisher:"Weaver Press"',
//   'inpublisher:"Modjaji Books"',
//   'inpublisher:"Sub-Saharan Publishers"',
//   'inpublisher:"Mkuki na Nyota"',
//   'inpublisher:"Wordweaver Publishing"',
//   'inpublisher:"Femrite"',
//   'inpublisher:"Huza Press"',
//   'inpublisher:"Bookcraft"',
//   'inpublisher:"Penguin Random House"',
//   'inpublisher:"Penguin Books"',
//   'inpublisher:"Random House"',
//   'inpublisher:"Knopf"',
//   'inpublisher:"Vintage"',
//   'inpublisher:"HarperCollins"',
//   'inpublisher:"William Morrow"',
//   'inpublisher:"Harper Perennial"',
//   'inpublisher:"Simon & Schuster"',
//   'inpublisher:"Scribner"',
//   'inpublisher:"Atria Books"',
//   'inpublisher:"Macmillan Publishers"',
//   'inpublisher:"Farrar, Straus and Giroux"',
//   'inpublisher:"St. Martin\'s Press"',
//   'inpublisher:"Hachette Book Group"',
//   'inpublisher:"Little, Brown and Company"',
//   'inpublisher:"Grand Central Publishing"',
//   'inpublisher:"Bloomsbury Publishing"',
//   'inpublisher:"Faber & Faber"',
//   'inpublisher:"W. W. Norton & Company"',
//   'inpublisher:"Atlantic Books"',
//   'inpublisher:"Canongate Books"',
//   'inpublisher:"Granta Books"',
//   'inpublisher:"New Directions"',
//   'inpublisher:"Grove Press"',
//   'inpublisher:"Algonquin Books"',
//   'inpublisher:"Chronicle Books"',
//   'inpublisher:"Melville House"',
//   'inpublisher:"Oxford University Press"',
//   'inpublisher:"Cambridge University Press"',
//   'inpublisher:"Harvard University Press"',
// ];

const allQueries = [
  // ...africanSubjects,
  ...globalSubjects,
  // ...africanAuthors,
  // ...globalAuthors,
  // ...awardQueries,
  // ...publisherQueries,
];

module.exports = {
  // africanSubjects,
  globalSubjects,
  // globalAuthors,
  // africanAuthors,
  // awardQueries,
  // publisherQueries,
  allQueries,
};
